# Change these first
owner: aulneau # Your GitHub username
repo: stacks-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Stacks Explorer
    url: https://explorer.stacks.co
  - name: Stacks node API (Mainnet)
    url: https://stacks-node-api.stacks.co
  - name: Transactions endpoint (confirmed)
    url: https://stacks-node-api.stacks.co/extended/v1/tx
  - name: Transactions endpoint (mempool)
    url: https://stacks-node-api.stacks.co/extended/v1/tx/mempool
  - name: Blocks endpoint
    url: https://stacks-node-api.stacks.co/extended/v1/block
  - name: Hiro.so
    url: https://hiro.so
  - name: stacks.co
    url: https://stacks.co

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /stacks-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Stacks Status
  introTitle: "A community run status checker for the Stacks ecosystem."
  introMessage: This is a simple status page for various properties in the Stacks ecosystem.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
