# Change these first
owner: aulneau # Your GitHub username
repo: stacks-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Stacks Explorer
    url: https://explorer.stacks.co
  - name: Stacks node API (Mainnet)
    url: https://stacks-node-api.stacks.co
  - name: Transactions endpoint (confirmed)
    url: https://stacks-node-api.stacks.co/extended/v1/tx
  - name: Transactions endpoint (mempool)
    url: https://stacks-node-api.stacks.co/extended/v1/tx/mempool
  - name: Blocks endpoint
    url: https://stacks-node-api.stacks.co/extended/v1/block
  - name: Hiro.so
    url: https://hiro.so
  - name: stacks.co
    url: https://stacks.co

status-website:
  cname: stacks-status.com
  logoUrl: http://blockstack-www.imgix.net/stx-logo-padded.svg
  name: Stacks Status
  introTitle: "A community run status checker for the Stacks ecosystem."
  introMessage: This is a simple status page for various properties in the Stacks ecosystem.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/30 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
